# Pasaana development environment
# Docker, Flask, databases
# MongoDB example: https://www.digitalocean.com/community/tutorials/how-to-set-up-flask-with-mongodb-and-docker
version: "3.7"

services:
  tasksapp-python:
    build: .
    # command: python app.py
    # volumes:
    #   - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    # env_file:
    #   - ./.env.dev
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - tasksapp-net

  mongo:
    image: mongo
    container_name: mongo
    # restart: unless-stopped
    # command: mongod --auth
    environment:
      # N.B. currently running without authentication
      # MONGO_INITDB_ROOT_USERNAME: mongodbuser
      # MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      # MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
    # MONDODB_LOG_DIR: /dev/null
    # ports:
    #   - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - tasksapp-net

volumes:
  mongodbdata:
    driver: local

networks:
  tasksapp-net:
